# docker-compose.yml / test-rp / ncp load balancer
version: '3'

networks:
  proxy:
    name: proxy

services:
  traefik:
    image: traefik:v2.9
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
    labels: 
      - "traefik.enable=true"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy    
      
  whoami1:
    image: traefik/whoami
    container_name: whoami1
    labels:
      - traefik.http.routers.whoami1.rule=PathPrefix(`/1`)
    networks:
      - proxy
  
  whoami2:
    image: traefik/whoami
    container_name: whoami2
    labels:
      - traefik.http.routers.whoami2.rule=PathPrefix(`/2`)
    networks:
      - proxy